# -*- coding: utf-8 -*-
"""Build a Simple AI Chain to Generate LinkedIn Posts_Mobarok_Hossen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16-zhUdqvMw7KK_Quuwn9witEkhvpIEma
"""

!pip install langchain openai langchain_openai langchain_community --quiet

# Import modules.

import os
from openai import OpenAI
from langchain.prompts import FewShotPromptTemplate, PromptTemplate
from langchain.chains import LLMChain

# Set up your GitHub token and endpoint
os.environ['GITHUB_TOKEN'] = "GIVE YOUR CODE HERE"  # Replace with your actual token
# Initialize the OpenAI client for LangChain using GitHub AI endpoint
token = os.environ["GITHUB_TOKEN"]
endpoint = "https://models.github.ai/inference"
model_name = "openai/gpt-4.1-nano"

client = OpenAI(
    base_url=endpoint,
    api_key=token,
)

# --- Few-shot examples and prompt engineering, as in your assignment ---
examples = [
    {
        "topic": "Artificial Intelligence",
        "language": "English",
        "post": "Artificial Intelligence is reshaping industries worldwide. From healthcare to finance, AI-driven solutions are unlocking efficiency and driving innovation. Embracing AI means staying ahead and future-proofing your career. #AI #Innovation"
    },
    {
        "topic": "Remote Work",
        "language": "English",
        "post": "Remote work has transformed the modern workplace, offering flexibility and new opportunities for collaboration. Success in remote environments depends on clear communication and trust. How has remote work changed your life? #RemoteWork #FutureOfWork"
    },
    {
        "topic": "Climate Change",
        "language": "English",
        "post": "Climate change is a global challenge demanding our attention and action. Sustainable practices in business can make a real difference. Let’s innovate for a greener tomorrow! #ClimateChange #Sustainability"
    }
]

example_template = """
Topic: {topic}
Language: {language}
LinkedIn Post: {post}
"""

few_shot_prompt = FewShotPromptTemplate(
    examples=examples,
    example_prompt=PromptTemplate(
        input_variables=["topic", "language", "post"],
        template=example_template,
    ),
    prefix="Given a topic and a language, write a clear, professional, and engaging LinkedIn post about the topic in the specified language.",
    suffix="""
Topic: {input_topic}
Language: {input_language}
LinkedIn Post:
""",
    input_variables=["input_topic", "input_language"]
)

# 2. Define your topics and languages to test
test_cases = [
    ("Artificial Intelligence", "English"),
    ("Remote Work", "English"),
    ("Climate Change", "English"),
    ("Personal Branding", "English"),
    ("Data Privacy", "English"),
    ("Artificial Intelligence", "Spanish"),
    ("Remote Work", "French")
]

for topic, language in test_cases:
    # Build prompt using LangChain template
    prompt = few_shot_prompt.format(
        input_topic=topic,
        input_language=language
    )

    # Call OpenAI
    response = client.chat.completions.create(
        messages=[
            {"role": "system", "content": "You are an expert LinkedIn content creator. Write a clear, engaging, and professional LinkedIn post about the given topic and Add 5 related Hashtags"},
            {"role": "user", "content": prompt}
        ],
        temperature=1.0,
        top_p=1.0,
        model=model_name
    )

    print(f"Topic: {topic} | Language: {language}\nPost:\n{response.choices[0].message.content}\n{'-'*60}\n")